---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: npm-install
  image: node:10
  commands: ["npm install"]

- name: test
  image: node:10
  commands: ["npm test"]

- name: release
  image: livingdocs/semantic-release:v2.1.1
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN
---
kind: signature
hmac: 0cee38eca6cecb238851a5e6cbeff2a091699b8ebd9692ea45c7c7ccfe353cc9

...
